### ISSUE TITLE
[Fix] 메인페이지 난이도 설정 기능 구현

### ISSUE THREAD

**Issue by eunsoo213** [CodeQuizz/CodeQuizz_main#19]
## 🤔 기능 설명
> 메인페이지 난이도 설정 기능 구현
>
> 
## 💻 작업 상세 내용
- [v] TODO
- [ ] 난이도 설정탭 위치 변경
## 참고할 수 있는 자료 (선택)

**Comment by hskhsmm** [comment]
완료
