### ISSUE TITLE
[Fix]메인페이지의 user점수 결과페이지로 전달 기능수정

### ISSUE THREAD

**Issue by eunsoo213** [CodeQuizz/CodeQuizz_main#29]
## 🤔 기능 설명
> 메인페이지의 user점수를 결과페이지로 전달하는 기능을 수정했습니다.
>
> 
## 💻 작업 상세 내용
- [v] TODO
- [ ] 
## 참고할 수 있는 자료 (선택)

**Comment by yejun235** [comment]
완료.
