### ISSUE TITLE
Refactor : 파일 구조 정리 및 디자인 흐름 개선

### ISSUE THREAD

**Issue by rawvv** [CodeQuizz/CodeQuizz_main#31]
## 🤔 기능 설명
> 추가하려는 기능에 대해 간결하게 설명해주세요
> 파일 구조 정리 및 디자인 흐름 개선
> 
## 💻 작업 상세 내용
- [v] TODO
- [ ] 파일 구조 정리
- [ ] 디자인 흐름 개선
## 참고할 수 있는 자료 (선택)

**Comment by yejun235** [comment]
완료.
