### ISSUE TITLE
Feat : 인터렉티브 기능 구현

### ISSUE THREAD

**Issue by rawvv** [CodeQuizz/CodeQuizz_main#57]
## 🤔 기능 설명
> 추가하려는 기능에 대해 간결하게 설명해주세요
>
> 
## 💻 작업 상세 내용
- [x] #72
- [x] 드래그 앤 드롭으로 코드 조각 맞추기
- [x] 코드 디버깅 퀴즈
- [x] 시각적 알고리즘 퍼즐
- [x] 실시간 코드 미리보기 
## 참고할 수 있는 자료 (선택)

**Comment by hskhsmm** [comment]
적용완료 했으니 이슈 닫겠습니다
